# Generated by Django 3.2.3 on 2021-05-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet',
            field=models.TextField(max_length=140),
        ),
    ]
