# Generated by Django 3.2.3 on 2021-06-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_alter_tweet_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet',
            field=models.TextField(),
        ),
    ]
